services:
  db:
    container_name: url_shortener_db_dev
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - url-shortener-dev-network

  backend:
    container_name: url_shortener_backend_dev
    image: url_shortener_backend:latest
    restart: always
    ports:
      - "8000:8000"
    build:
      context: ./backend
      target: dev
    volumes:
      - ./backend/app:/app/app
      - ./backend/alembic:/app/alembic
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - url-shortener-dev-network


volumes:
  pgdata_dev:

networks:
  url-shortener-dev-network:
