"""Rename fields

Revision ID: 381a6f7a07b3
Revises: 8319b902b2b6
Create Date: 2025-02-18 22:07:03.867615

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "381a6f7a07b3"
down_revision: Union[str, None] = "8319b902b2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shorturl", sa.Column("admin_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.drop_index("ix_shorturl_secret_key", table_name="shorturl")
    op.create_index(op.f("ix_shorturl_admin_key"), "shorturl", ["admin_key"], unique=False)
    op.drop_column("shorturl", "secret_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shorturl", sa.Column("secret_key", sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_shorturl_admin_key"), table_name="shorturl")
    op.create_index("ix_shorturl_secret_key", "shorturl", ["secret_key"], unique=False)
    op.drop_column("shorturl", "admin_key")
    # ### end Alembic commands ###
