"""Add separate AdminDetails model

Revision ID: 3a6be149feda
Revises: 381a6f7a07b3
Create Date: 2025-02-19 00:48:43.393507

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a6be149feda"
down_revision: Union[str, None] = "381a6f7a07b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admindetails",
        sa.Column("short_url_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
        sa.Column("client_host", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["short_url_id"],
            ["shorturl.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_url_id"),
    )
    op.create_index(op.f("ix_admindetails_admin_key"), "admindetails", ["admin_key"], unique=False)
    op.drop_index("ix_shorturl_admin_key", table_name="shorturl")
    op.drop_column("shorturl", "clicks")
    op.drop_column("shorturl", "admin_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shorturl", sa.Column("admin_key", sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column("shorturl", sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index("ix_shorturl_admin_key", "shorturl", ["admin_key"], unique=False)
    op.drop_index(op.f("ix_admindetails_admin_key"), table_name="admindetails")
    op.drop_table("admindetails")
    # ### end Alembic commands ###
