"""Create ShortUrl model

Revision ID: 8319b902b2b6
Revises: 83ba3d896a21
Create Date: 2025-02-18 21:13:17.529194

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8319b902b2b6"
down_revision: Union[str, None] = "83ba3d896a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shorturl",
        sa.Column("target_url", sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_path", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("secret_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_url"),
    )
    op.create_index(op.f("ix_shorturl_secret_key"), "shorturl", ["secret_key"], unique=False)
    op.create_index(op.f("ix_shorturl_short_path"), "shorturl", ["short_path"], unique=True)
    op.drop_index("ix_url_secret_key", table_name="url")
    op.drop_index("ix_url_short_url_key", table_name="url")
    op.drop_table("url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("short_url_key", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.Column("target_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
        sa.Column("secret_key", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("admin_url", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="url_pkey"),
    )
    op.create_index("ix_url_short_url_key", "url", ["short_url_key"], unique=True)
    op.create_index("ix_url_secret_key", "url", ["secret_key"], unique=True)
    op.drop_index(op.f("ix_shorturl_short_path"), table_name="shorturl")
    op.drop_index(op.f("ix_shorturl_secret_key"), table_name="shorturl")
    op.drop_table("shorturl")
    # ### end Alembic commands ###
